#!/usr/bin/env bash
# Purpose: Build a standalone installer script containing only selected modules.
#
# Usage:
#   INSTALL_SHELL=zsh INSTALL_RUNTIME=node INSTALL_EXTRAS=docker,git \
#     ./generate-script.sh ./dist/install.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES="${ROOT}/templates"
OUT_FILE="${1:-${ROOT}/dist/ubuntu-dev-env-install.sh}"

source "${TEMPLATES}/registry.sh"

: "${INSTALL_SHELL:=}"
: "${INSTALL_TERMINAL:=}"
: "${INSTALL_RUNTIME:=}"
: "${INSTALL_PKG_MANAGER:=}"
: "${INSTALL_EDITOR:=}"
: "${INSTALL_EXTRAS:=}"
: "${INSTALL_BROWSER:=chrome}"

declare -a LDW_PLAN_FILES=()
declare -a LDW_PLAN_CALLS=()
ldw_registry_plan_modules "${TEMPLATES}"

OUT_DIR="$(dirname "${OUT_FILE}")"
mkdir -p "${OUT_DIR}"

{
  printf '#!/usr/bin/env bash\n'
  printf 'set -euo pipefail\n\n'
  printf '# Generated by Linux Dev Wizard script composer\n'
  printf '# generated_at=%s\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  printf '# shell=%s terminal=%s runtime=%s pkg_manager=%s editor=%s extras=%s browser=%s\n\n' \
    "${INSTALL_SHELL:-none}" "${INSTALL_TERMINAL:-none}" "${INSTALL_RUNTIME:-none}" \
    "${INSTALL_PKG_MANAGER:-none}" "${INSTALL_EDITOR:-none}" "${INSTALL_EXTRAS:-none}" \
    "${INSTALL_BROWSER:-chrome}"

  printf '# ---- base.sh ----\n'
  sed '1{/^#!\/usr\/bin\/env bash$/d;}' "${TEMPLATES}/base.sh"
  printf '\n'

  for f in "${LDW_PLAN_FILES[@]}"; do
    printf '# ---- %s ----\n' "${f#"${ROOT}/"}"
    sed '1{/^#!\/usr\/bin\/env bash$/d;}' "${f}"
    printf '\n'
  done

  printf '# ---- generated execution plan ----\n'
  printf ': "${INSTALL_SHELL:=%s}"\n' "${INSTALL_SHELL}"
  printf ': "${INSTALL_TERMINAL:=%s}"\n' "${INSTALL_TERMINAL}"
  printf ': "${INSTALL_RUNTIME:=%s}"\n' "${INSTALL_RUNTIME}"
  printf ': "${INSTALL_PKG_MANAGER:=%s}"\n' "${INSTALL_PKG_MANAGER}"
  printf ': "${INSTALL_EDITOR:=%s}"\n' "${INSTALL_EDITOR}"
  printf ': "${INSTALL_EXTRAS:=%s}"\n' "${INSTALL_EXTRAS}"
  printf ': "${INSTALL_BROWSER:=%s}"\n' "${INSTALL_BROWSER}"
  printf '\n'
  printf 'ldw_log "Linux Dev Wizard — starting (standalone generated script)"\n'
  printf 'ldw_require_sudo\n'
  printf 'if ldw_have_apt; then\n'
  printf '  ldw_apt_install ca-certificates curl gnupg lsb-release\n'
  printf 'fi\n\n'

  for call in "${LDW_PLAN_CALLS[@]}"; do
    printf '%s\n' "${call}"
  done

  printf '\nif ldw_have_apt; then\n'
  printf '  ldw_apt_clean\n'
  printf 'fi\n'
  printf 'ldw_log "Linux Dev Wizard — finished successfully."\n'
} > "${OUT_FILE}"

chmod +x "${OUT_FILE}"

echo "Generated standalone script:"
echo "  ${OUT_FILE}"
echo
echo "Included module files:"
echo "  ${TEMPLATES}/base.sh"
for f in "${LDW_PLAN_FILES[@]}"; do
  echo "  ${f}"
done
