#!/usr/bin/env bash
# Purpose: Install Zsh, Oh My Zsh (unattended), Powerlevel10k, and popular plugins.
#          Idempotent where possible (skip OMZ if present, clone plugins if missing).
#
# Env: INSTALL_SHELL is driven by main.sh; this module also respects:
#   ZSH_THEME   — theme name (default: powerlevel10k/powerlevel10k)
#   ZSH_PLUGINS — space-separated plugin names for .zshrc (defaults below)
#
# Templating: {{ZSH_THEME}}, {{ZSH_PLUGINS}}, {{LDW_HOME}}

# Requires base.sh to be sourced by main.sh first.

ldw_shell_install_zsh() {
  ldw_log "Installing Zsh + Oh My Zsh stack"

  if ldw_have_apt; then
    ldw_apt_install zsh
  else
    ldw_die "apt not found; this module targets Debian/Ubuntu."
  fi

  local zsh_path
  zsh_path="$(command -v zsh)"
  if ! grep -q "^${zsh_path}\$" /etc/shells 2>/dev/null; then
    ldw_log "Registering ${zsh_path} in /etc/shells"
    echo "${zsh_path}" | sudo tee -a /etc/shells >/dev/null
  fi

  # --- Oh My Zsh (non-interactive) ---
  local omz_dir="${ZSH:-${LDW_HOME}/.oh-my-zsh}"
  export ZSH="${omz_dir}"

  if [[ ! -d "${ZSH}/.git" ]]; then
    ldw_log "Cloning Oh My Zsh (unattended)"
    RUNZSH=no CHSH=no KEEP_ZSHRC=yes git clone --depth=1 \
      https://github.com/ohmyzsh/ohmyzsh.git "${ZSH}"
  else
    ldw_log "Oh My Zsh already present at ${ZSH}; skipping clone"
  fi

  # --- Powerlevel10k theme ---
  local p10k_dir="${ZSH}/custom/themes/powerlevel10k"
  if [[ ! -d "${p10k_dir}/.git" ]]; then
    ldw_log "Installing Powerlevel10k theme"
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${p10k_dir}"
  else
    ldw_log "Powerlevel10k already present; skipping clone"
  fi

  # Default theme can be overridden by env or generator: {{ZSH_THEME}}
  : "${ZSH_THEME:=powerlevel10k/powerlevel10k}"

  # --- Third-party plugins (custom/plugins) ---
  local custom_plugins="${ZSH}/custom/plugins"
  mkdir -p "${custom_plugins}"

  _ldw_zsh_clone_plugin() {
    local name="$1"
    local url="$2"
    local dest="${custom_plugins}/${name}"
    if [[ ! -d "${dest}/.git" ]]; then
      ldw_log "Cloning zsh plugin: ${name}"
      git clone --depth=1 "${url}" "${dest}"
    fi
  }

  _ldw_zsh_clone_plugin zsh-autosuggestions https://github.com/zsh-users/zsh-autosuggestions
  _ldw_zsh_clone_plugin zsh-syntax-highlighting https://github.com/zsh-users/zsh-syntax-highlighting
  _ldw_zsh_clone_plugin zsh-completions https://github.com/zsh-users/zsh-completions

  # Plugin list: override with ZSH_PLUGINS env or substitute {{ZSH_PLUGINS}}
  : "${ZSH_PLUGINS:=git zsh-autosuggestions zsh-syntax-highlighting zsh-completions docker kubectl}"

  # --- Write ~/.zshrc if missing or we use a marker ---
  local zshrc="${LDW_HOME}/.zshrc"
  local marker="# Generated by Linux Dev Wizard"
  if [[ -f "${zshrc}" ]] && ! grep -qF "${marker}" "${zshrc}" 2>/dev/null; then
    ldw_warn ".zshrc exists without LDW marker; writing ${zshrc}.ldw-new — merge manually."
    zshrc="${LDW_HOME}/.zshrc.ldw-new"
  fi

  ldw_log "Writing ${zshrc}"
  umask 077
  {
    printf '%s\n' "${marker}"
    printf '%s\n' "# Templated values: theme={{ZSH_THEME}} plugins={{ZSH_PLUGINS}}"
    printf 'export ZSH="%s"\n' "${ZSH}"
    printf 'ZSH_THEME="%s"\n' "${ZSH_THEME}"
    printf 'plugins=(%s)\n' "${ZSH_PLUGINS}"
    printf '\n%s\n\n' 'source $ZSH/oh-my-zsh.sh'
    # Literal zsh syntax (do not let bash expand $ or %)
    cat <<'P10K'
# Powerlevel10k instant prompt (optional; comment out if you use another theme)
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
P10K
  } > "${zshrc}"

  # Optional: set login shell to zsh (can be disabled with SET_DEFAULT_SHELL=no)
  : "${SET_DEFAULT_SHELL:=yes}"
  if [[ "${SET_DEFAULT_SHELL}" == "yes" ]] && [[ -n "${SUDO_USER:-}" ]]; then
    ldw_log "Setting default shell to zsh for ${SUDO_USER}"
    sudo chsh -s "${zsh_path}" "${SUDO_USER}"
  elif [[ "${SET_DEFAULT_SHELL}" == "yes" ]] && [[ -z "${SUDO_USER:-}" ]]; then
    chsh -s "${zsh_path}" || ldw_warn "chsh failed; set default shell manually."
  fi

  ldw_log "Zsh setup complete. Open a new terminal or run: exec zsh"
}
